apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hellofront
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - hellofront
  selector:
    matchLabels:
      app: hellofront
  podTargetLabels:
    - version
  endpoints:
  - port: http
